apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: beleganski-jaas
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: alex-jaas.dporkov.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: beleganski-jaas
                port:
                  number: 80
